# Generated by Django 3.2.16 on 2023-04-06 06:11

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Album Title')),
                ('released_year', models.IntegerField(validators=[blog.models.validate_year])),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Blog Title')),
                ('genre', models.CharField(choices=[('deshbhakti', 'DeshBhakti'), ('friendship', 'Friedship'), ('ghazal', 'Ghazal'), ('bhakti', 'Bhakti')], default='N/A', max_length=20)),
                ('keywords', models.CharField(default=models.CharField(max_length=500, verbose_name='Blog Title'), max_length=5000, verbose_name='Keywords')),
                ('album', models.ManyToManyField(blank=True, to='blog.Album')),
                ('author', models.ManyToManyField(blank=True, to='blog.Author')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ManyToManyField(blank=True, to='blog.Author'),
        ),
    ]
